language: go
go:
  - master 
services:
  - postgresql
before_script:
  - psql -c 'create database food_test;' -U postgres
  - psql food_test < food.sql
  addons:
    postgresql: "10"
    apt:
      packages:
        - postgresql-10
        - postgresql-client-10
dist: trusty
env:
  global:
    - PGPORT=5433
branches:
  only:
    - master
