language: go
go:
  - master 
script: ./run-api.sh
services:
  - postgres
before_script:
  - psql -c 'create database food_test;' -U postgres
  - psql food_test < food.sql
  addons:
    postgresql = "10"
